
[ingame]
	#Range: 0.0 ~ 1.0
	laser_pointer_color = 0.0936073059360731
	show_health_indicator = false
	#Range: 1 ~ 10
	long_press_count = 2
	enable_laser_pointer = true
	auto_preparation = true
	mining_autoswitch_items = []
	camera_auto_switch = false
	filter_animation = false
	off_gore = true
	show_target_indicator = false
	battle_autoswitch_items = []

